apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            cpu: "50m"     # CPU limite em milicores
            memory: "64Mi" # Limite de mem贸ria em Mebibytes
          requests:
            cpu: "50m"     # CPU solicitada em milicores
            memory: "64Mi" # Mem贸ria solicitada em Mebibytes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-high
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-high
  template:
    metadata:
      labels:
        app: nginx-high
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            cpu: "100m"     # CPU limite em milicores
            memory: "128Mi" # Limite de mem贸ria em Mebibytes
          requests:
            cpu: "100m"     # CPU solicitada em milicores
            memory: "128Mi" # Mem贸ria solicitada em Mebibytes
